# Deploy PsiCAT Home to personal home network.

name: .NET

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - '*.md'
      - '.gitignore'

jobs:
  build:

    runs-on: urshanabi

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: dotnet build --configuration Release ./PsiCat-Home/PsiCat-Home.csproj
    - name: Stop PsiCAT Home Service
      continue-on-error: true
      run: sudo /usr/bin/systemctl stop psicat-home.service
    - name: Publish
      run: dotnet publish -c Release -o /var/www/html ./PsiCat-Home/PsiCat-Home.csproj
    - name: Start PsiCAT Home Service
      run: sudo /usr/bin/systemctl start psicat-home.service
